In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from jqdatasdk import *
from fac_calc import solve_flag
from extract_fac import extract_fac
import plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
import cufflinks
from plotly.subplots import make_subplots
from concurrent.futures import ProcessPoolExecutor
from backtrade import back_trade
cufflinks.go_offline(connected=True)
init_notebook_mode(connected=True)
import warnings
warnings.filterwarnings("ignore")

'''
    这里只回测了 2022 年 到 2023-04 的数据
    因为分钟级别的数据太大了，下载也慢，算的也慢
    我看研报里面给了一部分了，前面的部分就默认他是对的了，来看看后续的表现怎么样

    研报 pdf 确实不太方便直接放， Wind 下载的，有水印
    这里放个图片版链接吧 url = https://mp.weixin.qq.com/s/DUGqlyNkhGtb3T08C9N-HQ

    另外分钟级别的数据建议也不要找我要，我确实也不全…… 上传也太慢了。
'''

In [2]:
def login():
    auth('Name', 'Password')
    print(get_query_count())

In [3]:
# 计算因子值

login()
begin_date = "2020-01-01"
end_date= "2023-04-17"
cpu_workers = 8

auth success
{'total': 200000000, 'spare': 2647330}

In [4]:
# trade_cal = get_trade_days(start_date=begin_date, end_date=end_date)
# trade_cal = [_.strftime("%Y-%m-%d") for _ in trade_cal]
# with ProcessPoolExecutor(max_workers=cpu_workers) as pool:
#     pool.map(solve_flag, trade_cal)

In [5]:
df = extract_fac("2022-01-01", "2023-04-17")
df.to_pickle("fac1.pkl")
df

                code  vol_spot        date  spot_count  ret_spot
0        000001.XSHE  0.000250  2022-01-04          19  0.000045
1        000002.XSHE  0.000109  2022-01-04          23  0.000242
2        000004.XSHE  0.000118  2022-01-04          12  0.000141
3        000005.XSHE  0.000142  2022-01-04          18  0.000073
4        000006.XSHE  0.000099  2022-01-04          15  0.000048
...              ...       ...         ...         ...       ...
1489244  688799.XSHG  0.000081  2023-04-17          12  0.000020
1489245  688800.XSHG  0.000076  2023-04-17          18  0.000011
1489246  688819.XSHG  0.000122  2023-04-17          21  0.000010
1489247  688981.XSHG  0.000231  2023-04-17          18 -0.000061
1489248  689009.XSHG  0.000265  2023-04-17          30 -0.000027

[1489249 rows x 5 columns]

首先来看看贵州茅台的激增时刻的次数分布

In [6]:

gzmt = df[df["code"] == "600519.XSHG"]
print(gzmt["spot_count"].describe())

count    311.000000
mean      20.839228
std        4.919993
min        6.000000
25%       18.000000
50%       21.000000
75%       24.500000
max       34.000000
Name: spot_count, dtype: float64

这里是 21 次，研报是 22 次，不同的主要原因是时间区间不一样，自己测试了一下 14 - 22, 平均大概 21.8 ，总体处于可接受范围内

这里次数变少可能也说明白酒确实也没有以前强势了

接下来合成一下他的四个基础因子，月均/稳 耀眼 波动/收益率因子

In [7]:
# 首先要减去每天的截面的均值
df["vol_spot_minus_mean"] = df["vol_spot"] - df.groupby("date")["vol_spot"].transform("mean")
df["vol_spot_minus_mean"] = df["vol_spot_minus_mean"].apply(abs)
df["ret_spot_minus_mean"] = df["ret_spot"] - df.groupby("date")["ret_spot"].transform("mean")
df["ret_spot_minus_mean"] = df["ret_spot_minus_mean"].apply(abs)
df

,code,vol_spot,date,spot_count,ret_spot,vol_spot_minus_mean,ret_spot_minus_mean
0,000001.XSHE,0.000250,2022-01-04,19,0.000045,0.000111,2.095950e-06
1,000002.XSHE,0.000109,2022-01-04,23,0.000242,0.000030,1.953467e-04
2,000004.XSHE,0.000118,2022-01-04,12,0.000141,0.000021,9.399119e-05
3,000005.XSHE,0.000142,2022-01-04,18,0.000073,0.000003,2.584735e-05
4,000006.XSHE,0.000099,2022-01-04,15,0.000048,0.000040,9.738135e-07
...,...,...,...,...,...,...,...
1489244,688799.XSHG,0.000081,2023-04-17,12,0.000020,0.000039,8.764080e-06
1489245,688800.XSHG,0.000076,2023-04-17,18,0.000011,0.000044,5.258242e-07
1489246,688819.XSHG,0.000122,2023-04-17,21,0.000010,0.000002,1.720020e-06
1489247,688981.XSHG,0.000231,2023-04-17,18,-0.000061,0.000111,7.206735e-05
1489248,689009.XSHG,0.000265,2023-04-17,30,-0.000027,0.000145,3.873808e-05

In [8]:
# 然后按照代码分组滚动 20 天，计算每天的 vol_spot_minus_mean 和 ret_spot_minus_mean 的均值
df["fac1"] = df.groupby("code", as_index = False)["vol_spot_minus_mean"].apply(lambda x: x.rolling(20).mean())
df["fac2"] = df.groupby("code", as_index = False)["vol_spot_minus_mean"].apply(lambda x: x.rolling(20).std())
df["fac3"] = df.groupby("code", as_index = False)["ret_spot_minus_mean"].apply(lambda x: x.rolling(20).mean())
df["fac4"] = df.groupby("code", as_index = False)["ret_spot_minus_mean"].apply(lambda x: x.rolling(20).std())

In [26]:
def show(df, Name):
    df["date"] = pd.to_datetime(df["date"])
    trace0 = go.Scatter(x = df["date"], y = df["ret_0"], name = "group_0")
    trace1 = go.Scatter(x = df["date"], y = df["ret_1"], name = "group_1")
    trace2 = go.Scatter(x = df["date"], y = df["ret_2"], name = "group_2")
    trace3 = go.Scatter(x = df["date"], y = df["ret_3"], name = "group_3")
    trace4 = go.Scatter(x = df["date"], y = df["ret_4"], name = "group_4")
    trace5 = go.Scatter(x = df["date"], y = df["ret_5"], name = "group_5")
    trace6 = go.Scatter(x = df["date"], y = df["ret_6"], name = "group_6")
    trace7 = go.Scatter(x = df["date"], y = df["ret_7"], name = "group_7")
    trace8 = go.Scatter(x = df["date"], y = df["ret_8"], name = "group_8")
    trace9 = go.Scatter(x = df["date"], y = df["ret_9"], name = "group_9")

    

    fig = make_subplots(specs=[[{'secondary_y': True}]])
    
    data = [trace0, trace1, trace2, trace3, trace4, trace5, trace6, trace7, trace8, trace9]
    fig.add_traces(data)

    fig.add_trace(
        go.Scatter(x=df["date"], y=df["ret_0"] - df["ret_9"], name="多空差异"),
        secondary_y=True,
    )
    
    fig.update_layout(
        title = Name, 
        xaxis_title = "Date",
        yaxis_title = "Return",
    )

    fig.show()

In [27]:
# fac1 回测

fac1_df = back_trade(df, "fac1")
show(fac1_df, "fac1")

In [28]:

fac2_df = back_trade(df, "fac2")
show(fac2_df, "fac2")

In [29]:
fac3_df = back_trade(df, "fac2")
show(fac3_df, "fac3")

In [30]:
fac4_df = back_trade(df, "fac4")
show(fac4_df, "fac4")

多空对冲还可以，相对来说比较稳定了

文中并没有详细说明如何合成因子，等权合成，或许是求 rank 的和？有好的意见可以提供给我哈~

这里补充说明一下：按照券商研报的想法，因子值越小，应该代表着“多”，因子值越大，应该代表着 “空”

实际跑出来表现最好前三个是 $group_0$ ，第四个是 $group_1$，表现最差的很稳定是最后一组，作为负向指标来说还是挺好用的

个人感觉不应该取绝对值，直接放去均值后的值进来应该会表现更好，简单测试一下

In [31]:
df["my_vol_spot_minus_mean"] = df["vol_spot"] - df.groupby("date")["vol_spot"].transform("mean")
df["my_ret_spot_minus_mean"] = df["ret_spot"] - df.groupby("date")["ret_spot"].transform("mean")

df["fac5"] = df.groupby("code", as_index = False)["vol_spot_minus_mean"].apply(lambda x: x.rolling(20).mean())
df["fac6"] = df.groupby("code", as_index = False)["vol_spot_minus_mean"].apply(lambda x: x.rolling(20).std())
df["fac7"] = df.groupby("code", as_index = False)["ret_spot_minus_mean"].apply(lambda x: x.rolling(20).mean())
df["fac8"] = df.groupby("code", as_index = False)["ret_spot_minus_mean"].apply(lambda x: x.rolling(20).std())

In [32]:
fac5_df = back_trade(df, "fac5")
show(fac5_df, "fac5")

In [33]:
fac6_df = back_trade(df, "fac6")
show(fac6_df, "fac6")

In [34]:
fac7_df = back_trade(df, "fac7")
show(fac7_df, "fac7")

In [35]:
fac8_df = back_trade(df, "fac8")
show(fac8_df, "fac8")

多空收益看起来更明显了一些

作为多因子模型中一个因子应该是勉强够用了

是一篇很符合我对券商研报印象的研报hhhhhhhh