In [56]:
# 风险及免责提示：该策略由聚宽用户在聚宽社区分享，仅供学习交流使用。
# 原文一般包含策略说明，如有疑问请到原文和作者交流讨论。
# 原文网址：https://www.joinquant.com/view/community/detail/38296
# 标题：FoF, all in
# 作者：Gyro

import numpy as np
import pandas as pd
import datetime as dt
from jqdata import *
from jqfactor import *
from six import *

In [57]:
# set option
pd.set_option('display.width', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [58]:
# parameter
index = '000300.XSHG' # market index
mday = 21
nday = 241
rday = sqrt(nday)

In [59]:
# last day
h = history(1, '1d', 'close', index)
dt_last = h.index[0].date()
dt_last

datetime.date(2022, 6, 24)

In [60]:
# all fund
all_fund = get_all_securities('fund', dt_last)
len(all_fund)

1198

In [61]:
all_fund.head()

            display_name      name  start_date    end_date type
159001.XSHE        货币ETF       BZJ  2014-10-20  2200-01-01  etf
159003.XSHE      招商快线ETF      ZSKX  2014-10-20  2200-01-01  etf
159005.XSHE     汇添富快钱ETF      TFKQ  2015-01-13  2200-01-01  etf
159601.XSHE       A50ETF    A50ETF  2021-11-08  2200-01-01  etf
159602.XSHE     中国A50ETF  ZGA50ETF  2021-11-08  2200-01-01  etf

In [62]:
# filter, on list 1-year
dt_1y = dt_last - dt.timedelta(days=365)
all_fund = all_fund[all_fund.start_date < dt_1y]
funds = all_fund.index.tolist()
len(funds)

960

In [63]:
# shares
ff = finance.run_query(query(
        finance.FUND_SHARE_DAILY
    ).filter(
        finance.FUND_SHARE_DAILY.code.in_(funds),
        finance.FUND_SHARE_DAILY.date==dt_last,
    )).set_index('code')
shares = ff.shares
shares.head()

code
159001.XSHE    25539800
159003.XSHE     3314700
159005.XSHE      382600
159702.XSHE    18931000
159703.XSHE    56581500
Name: shares, dtype: int64

In [64]:
#  filter, size
price = history(1, '1d', 'close', funds).iloc[0]
value = price*shares
value = value[value > 1e8].dropna()
funds = value.index.tolist()
len(funds)

443

In [65]:
# filter, liquidity
h = history(mday, '1d', 'money', funds+[index])
hm = h.min()
hx = 1e-6*h[index].mean()
funds = [s for s in funds if hm[s] > hx]
len(funds), hx/10000

(353, 30.30354752809524)

In [66]:
#  history return
h = history(nday, '1d', 'close', funds+[index])
r = np.log(h).diff()[1:]
rx = r[index]

In [67]:
# filter, volatility
V = 100*rday*r.std()
Vx = V[index]
V = V[V > 1.0]
V = V[V < Vx]
V = V.sort_values()
funds = V.index.tolist()
len(funds)

78

In [68]:
# weight
w = 1.0/V
weight = 0.95*w/w.sum()
funds = weight.index.tolist()

In [69]:
# report
df = pd.DataFrame(index=funds)
df['Value'] = 1e-8*value[funds]
df['Volatility'] = V
df['Weight'] = 100*weight
df['Name'] = all_fund.display_name[funds]
df

                  Value  Volatility    Weight         Name
511030.XSHG   52.554836    1.099327  8.206155          公司债
161716.XSHE   11.390424    1.284193  7.024840      招商双债LOF
511010.XSHG    8.059388    1.749789  5.155621        国债ETF
511220.XSHG   12.521523    1.825777  4.941046        城投ETF
511060.XSHG    5.603295    1.868562  4.827910         5年地债
161911.XSHE    1.395983    1.915922  4.708566     万家强化收益定开
161115.XSHE    3.183241    1.933686  4.665311    易基岁丰添利LOF
511260.XSHG    7.458948    2.097523  4.300905         十年国债
511270.XSHG    7.059673    2.115388  4.264582        10年地债
159816.XSHE   16.817444    2.180358  4.137508     0-4地债ETF
159972.XSHE   39.190054    2.295954  3.929194      5年地债ETF
184801.XSHE   16.148193    3.694455  2.441834     鹏华前海REIT
511180.XSHG    1.329162    7.866747  1.146757         上证转债
180201.XSHE   84.458714    9.282454  0.971860   平安广州广河REIT
511380.XSHG    7.617210   11.397473  0.791513        转债ETF
518880.XSHG  100.104400   12.048894  0.748720        黄金ETF
159937.XSHE   63.540519   12.080544  0.746758      黄金ETF基金
159934.XSHE   39.229580   12.083863  0.746553        黄金ETF
518850.XSHG    1.428117   12.092278  0.746034       黄金9999
518660.XSHG    1.012042   12.180447  0.740634         工银黄金
518800.XSHG    6.434867   12.232181  0.737501         黄金基金
518680.XSHG    1.421035   12.261669  0.735728         金ETF
160706.XSHE    3.921880   15.083782  0.598076     沪深300LOF
501050.XSHG    5.650675   15.202707  0.593397         50AH
510760.XSHG    2.271409   15.224587  0.592545        上证ETF
510210.XSHG    6.904235   15.417072  0.585147        综指ETF
161017.XSHE    1.839334   15.869509  0.568464     500增强LOF
160505.XSHE    6.246110   15.910775  0.566990      博时主题LOF
160119.XSHE    1.476349   16.403920  0.549945  500ETF联接LOF
515330.XSHG   66.847430   16.639269  0.542166        天弘300
510180.XSHG  210.484855   16.939746  0.532549       180ETF
517080.XSHG    5.783751   17.179443  0.525119       HGS500
515450.XSHG    2.306307   17.208631  0.524228         红利50
515770.XSHG    1.265539   17.333325  0.520457     MSCIAETF
515100.XSHG    1.419901   17.406495  0.518269      低波红利ETF
161005.XSHE   26.810351   17.413728  0.518054      富国天惠LOF
501080.XSHG    5.801560   17.416926  0.517959         科创中金
163402.XSHE   14.495009   17.473613  0.516278      兴全趋势LOF
512750.XSHG    1.331276   17.492800  0.515712        基本面50
512380.XSHG    2.048999   17.591536  0.512817       MSCI中国
512990.XSHG    3.141859   17.679550  0.510265       MSCIA股
159887.XSHE    3.954240   17.767970  0.507725        银行ETF
513500.XSHG   62.742731   17.863424  0.505012        标普500
510810.XSHG   68.624854   17.906102  0.503809         上海国企
515800.XSHG   19.609765   18.129925  0.497589       800ETF
515350.XSHG    1.337826   18.212289  0.495338        民生300
515020.XSHG    6.175167   18.216935  0.495212         华夏银基
510350.XSHG   31.167230   18.224337  0.495011        工银300
510360.XSHG   16.093343   18.252143  0.494257        广发300
516310.XSHG    1.701012   18.252802  0.494239         银行指基
515780.XSHG    2.123707   18.296877  0.493048       浦银MSCI
515810.XSHG    1.054242   18.312853  0.492618     ZZ800ETF
512510.XSHG    5.270592   18.318003  0.492480       ETF500
159925.XSHE   17.646363   18.327880  0.492214   沪深300ETF南方
510310.XSHG  107.228126   18.426570  0.489578     HS300ETF
501029.XSHG    2.935609   18.428984  0.489514         红利基金
512730.XSHG    1.866131   18.483629  0.488067       银行FUND
512160.XSHG    5.088649   18.590010  0.485274       MSCI基金
510390.XSHG    6.322453   18.603735  0.484916        平安300
159919.XSHE  184.338201   18.645161  0.483839     沪深300ETF
512700.XSHG   27.144729   18.646064  0.483815         银行基金
515290.XSHG   70.883636   18.697806  0.482476           银行
510580.XSHG   19.668250   18.702930  0.482344     ZZ500ETF
512090.XSHG    4.818154   18.722146  0.481849       MSCI易基
510800.XSHG    5.597929   18.724524  0.481788         上证50
163406.XSHE   12.386052   18.746671  0.481219      兴全合润LOF
512820.XSHG    5.156933   18.776850  0.480445         银行股基
159976.XSHE    1.420410   18.784889  0.480240        湾创ETF
510100.XSHG    7.864671   18.796517  0.479942      SZ50ETF
515380.XSHG   40.356855   18.801929  0.479804        泰康300
517300.XSHG   23.403646   18.839092  0.478858     AH300ETF
515390.XSHG    5.268484   18.908688  0.477095        HS300
512800.XSHG  103.531139   18.930478  0.476546        银行ETF
510300.XSHG  466.815423   19.030834  0.474033       300ETF
510330.XSHG  222.653777   19.113837  0.471975        华夏300
512910.XSHG    3.647480   19.145855  0.471185       100ETF
159982.XSHE    3.737770   19.341629  0.466416   中证500ETF鹏华
510710.XSHG    5.713973   19.348049  0.466261       上50ETF

In [70]:
# feature
Rp = np.dot(r[funds], weight)
100*240*Rp.mean(), 100*15.5*Rp.std()

(0.007131749725057535, 4.631950479977869)