In [1]:
import numpy as np
import pandas as pd
import datetime as dt
from jqdata import *
import statsmodels.api as sm

In [2]:
# 信息设置
pd.set_option('display.width', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
#
# 基金市场研究
#

In [7]:
#  参数
index = '399311.XSHE'

In [8]:
# 当前
dt_now = dt.datetime.now().date()
dt_now

datetime.date(2023, 4, 25)

In [9]:
# 股票池
stocks = get_index_stocks(index)

In [11]:
# 数据段
dt_end = dt.date(2023, 3, 31)
reportId = 403001 # 年度403006，半年度403005，第一季度403001

In [12]:
# 测试
# 注意：code和symbol的格式，没有后缀！
stock = '600519'
df = finance.run_query(query(
        finance.FUND_PORTFOLIO_STOCK
    ).filter(
        finance.FUND_PORTFOLIO_STOCK.symbol == stock,
        finance.FUND_PORTFOLIO_STOCK.period_end == dt_end,
        finance.FUND_PORTFOLIO_STOCK.report_type_id == reportId,
    ).limit(5)
    )
df

,id,code,period_start,period_end,pub_date,report_type_id,report_type,rank,symbol,name,shares,market_cap,proportion
0,150658167,000165,2023-01-01,2023-03-31,2023-04-20,403001,第一季度,3,600519,贵州茅台,9701.0,17655820.0,2.38
1,150658186,000259,2023-01-01,2023-03-31,2023-04-20,403001,第一季度,2,600519,贵州茅台,7500.0,13650000.0,2.79
2,150658196,000336,2023-01-01,2023-03-31,2023-04-20,403001,第一季度,2,600519,贵州茅台,108600.0,197652000.0,5.26
3,150658226,000551,2023-01-01,2023-03-31,2023-04-20,403001,第一季度,2,600519,贵州茅台,30000.0,54600000.0,5.79
4,150658275,000845,2023-01-01,2023-03-31,2023-04-20,403001,第一季度,1,600519,贵州茅台,2200.0,4004000.0,8.17

In [13]:
# 逐股提取基金持仓
fportfolio = pd.Series()
for s in stocks:
    stock = s[:6]
    df = finance.run_query(query(
            finance.FUND_PORTFOLIO_STOCK
        ).filter(
            finance.FUND_PORTFOLIO_STOCK.symbol == stock,
            finance.FUND_PORTFOLIO_STOCK.period_end == dt_end,
            finance.FUND_PORTFOLIO_STOCK.report_type_id == reportId,
        ).order_by(finance.FUND_PORTFOLIO_STOCK.market_cap.desc())                           
        )
    total_value = 1e-8*df.market_cap.sum()
    fportfolio[s] = total_value
    print(s, get_security_info(s).display_name, total_value) # 提取数据过程很长，需要不停输出信息以示运行进度

000001.XSHE 平安银行 98.39244423259998
000002.XSHE 万科A 91.6966556208
000009.XSHE 中国宝安 0.11706552
000012.XSHE 南玻A 0.6050407
000021.XSHE 深科技 2.36449224
000027.XSHE 深圳能源 0.01877603
000031.XSHE 大悦城 0.00860884
000032.XSHE 深桑达A 39.5905570206
000035.XSHE 中国天楹 6.3627285405
000039.XSHE 中集集团 0.05161863
000050.XSHE 深天马A 0.05961272
000060.XSHE 中金岭南 2.04082584
000062.XSHE 深圳华强 0.015696881200000002
000063.XSHE 中兴通讯 159.036293548
000066.XSHE 中国长城 7.772955081999999
000069.XSHE 华侨城A 12.400369086
000089.XSHE 深圳机场 0.034263
000100.XSHE TCL科技 20.222813954499998
000155.XSHE 川能动力 2.1710451056
000156.XSHE 华数传媒 0.19535688
000157.XSHE 中联重科 0.57488454
000166.XSHE 申万宏源 24.7248515283
000301.XSHE 东方盛虹 12.17717211
000333.XSHE 美的集团 215.10357712130002
000338.XSHE 潍柴动力 19.5455300118
000400.XSHE 许继电气 8.05026924
000401.XSHE 冀东水泥 2.1310582216
000402.XSHE 金融街 0.08352276
000403.XSHE 派林生物 2.6934321088
000408.XSHE 藏格矿业 1.9128034928
000415.XSHE 渤海租赁 0.0216426
000423.XSHE 东阿阿胶 44.2425453946
000425.XSHE 徐工机械 23.9731442181
000513.XSHE 丽珠集团 6.068487499200001
000516.XSHE 国际医学 23.410816525
000519.XSHE 中兵红箭 2.5449851428
000528.XSHE 柳工 0.5120002060000001
000537.XSHE 广宇发展 0.019499
000538.XSHE 云南白药 2.9142929250000003
000540.XSHE 中天金融 0.0
000547.XSHE 航天发展 0.0693
000553.XSHE 安道麦A 0.0
000559.XSHE 万向钱潮 0.01933575
000563.XSHE 陕国投A 0.181481652
000568.XSHE 泸州老窖 1129.6200590667
000581.XSHE 威孚高科 1.7592300087000001
000582.XSHE 北部湾港 0.0
000591.XSHE 太阳能 1.4180680940000001
000596.XSHE 古井贡酒 354.42686576
000598.XSHE 兴蓉环境 1.8044718
000617.XSHE 中油资本 0.26856248
000623.XSHE 吉林敖东 1.7017201259
000625.XSHE 长安汽车 30.6130215992
000627.XSHE 天茂集团 0.0
000629.XSHE 钒钛股份 0.94735862
000630.XSHE 铜陵有色 14.4114435276
000636.XSHE 风华高科 2.191755456
000651.XSHE 格力电器 105.6173600475
000656.XSHE 金科股份 0.0
000661.XSHE 长春高新 138.60089786199998
000672.XSHE 上峰水泥 0.043451500000000004
000683.XSHE 远兴能源 65.7192764716
000686.XSHE 东北证券 0.0049225512
000688.XSHE 国城矿业 0.0
000703.XSHE 恒逸石化 0.40993178519999995
000708.XSHE 中信特钢 11.23222163
000709.XSHE 河钢股份 0.09862191000000001
000712.XSHE 锦龙股份 0.0
000723.XSHE 美锦能源 5.8914981719999995
000725.XSHE 京东方A 42.735679675200004
000728.XSHE 国元证券 2.08936728
000729.XSHE 燕京啤酒 14.2601336994
000733.XSHE 振华科技 179.26294310939994
000738.XSHE 航发控制 23.8485213624
000739.XSHE 普洛药业 33.163716174
000750.XSHE 国海证券 0.0
000762.XSHE 西藏矿业 8.110210573900002
000768.XSHE 中航西飞 56.593656547100004
000776.XSHE 广发证券 41.549529826699995
000778.XSHE 新兴铸管 1.0903620390000002
000783.XSHE 长江证券 0.42231294399999997
000785.XSHE 居然之家 1.8352229635
000786.XSHE 北新建材 4.40788623
000792.XSHE 盐湖股份 23.154044742399996
000799.XSHE 酒鬼酒 51.001742034900005
000800.XSHE 一汽解放 0.048472
000807.XSHE 云铝股份 37.763005554
000818.XSHE 航锦科技 3.975465648
000825.XSHE 太钢不锈 1.1776804396
000830.XSHE 鲁西化工 1.0399880400000001
000831.XSHE 中国稀土 2.2884196599
000858.XSHE 五粮液 1175.44670044
000860.XSHE 顺鑫农业 29.973302135
000869.XSHE 张裕A 0.010432
000875.XSHE 吉电股份 0.0
000876.XSHE 新希望 9.7907294646
000877.XSHE 天山股份 1.1009391700000002
000878.XSHE 云南铜业 4.6046008608
000883.XSHE 湖北能源 0.0
000887.XSHE 中鼎股份 0.39284779760000005
000893.XSHE 亚钾国际 13.054611798800002
000895.XSHE 双汇发展 11.793654462600003
000898.XSHE 鞍钢股份 1.2265403832
000902.XSHE 新洋丰 1.6064013468
000927.XSHE 中国铁物 0.0
000930.XSHE 中粮科技 0.0
000932.XSHE 华菱钢铁 10.6201788031
000933.XSHE 神火股份 84.2382765776
000935.XSHE 四川双马 9.2852756078
000937.XSHE 冀中能源 2.2266803304000002
000938.XSHE 紫光股份 62.18889119599999
000951.XSHE 中国重汽 13.132380022199998
000958.XSHE 电投产融 0.0
000959.XSHE 首钢股份 1.5240000000000001e-07
000960.XSHE 锡业股份 3.3303554384
000963.XSHE 华东医药 122.5929204248
000966.XSHE 长源电力 0.0
000967.XSHE 盈峰环境 0.3140888832
000970.XSHE 中科三环 0.087508
000975.XSHE 银泰黄金 91.95228887519998
000977.XSHE 浪潮信息 16.669227627
000983.XSHE 山西焦煤 27.908218107
000987.XSHE 越秀资本 0.9493105221000001
000988.XSHE 华工科技 11.470858914900003
000990.XSHE 诚志股份 0.0
000997.XSHE 新大陆 3.2987750256
000998.XSHE 隆平高科 49.472181104600004
000999.XSHE 华润三九 68.07069072899999
001203.XSHE 大中矿业 0.0
001213.XSHE 中铁特货 0.0
001227.XSHE 兰州银行 0.0
001289.XSHE 龙源电力 0.0128982
001872.XSHE 招商港口 0.08708454
001914.XSHE 招商积余 9.6078647488
001965.XSHE 招商公路 0.7995347128999999
001979.XSHE 招商蛇口 106.98982777440001
002001.XSHE 新和成 3.30374417
002007.XSHE 华兰生物 2.8069221384999996
002008.XSHE 大族激光 0.9867431455
002010.XSHE 传化智联 0.1822737
002019.XSHE 亿帆医药 0.0970722792
002025.XSHE 航天电器 43.7630391128
002027.XSHE 分众传媒 53.9093006886
002028.XSHE 思源电气 77.42811158999999
002030.XSHE 达安基因 0.4751952201
002032.XSHE 苏泊尔 15.467921508
002044.XSHE 美年健康 27.546412408000002
002048.XSHE 宁波华翔 15.273810249700002
002049.XSHE 紫光国微 168.34312791189998
002050.XSHE 三花智控 170.6999885775
002056.XSHE 横店东磁 46.20986937440001
002064.XSHE 华峰化学 0.5043816408
002065.XSHE 东华软件 0.40005427299999996
002074.XSHE 国轩高科 19.659371561500002
002078.XSHE 太阳纸业 69.0923866875
002080.XSHE 中材科技 10.555111820899999
002081.XSHE 金螳螂 1.8126353672
002085.XSHE 万丰奥威 3.5811516891999995
002091.XSHE 江苏国泰 0.0
002092.XSHE 中泰化学 1.785803325
002110.XSHE 三钢闽光 0.3432254
002120.XSHE 韵达股份 29.5001487508
002124.XSHE 天邦食品 0.26700416
002127.XSHE 南极电商 0.0
002128.XSHE 电投能源 1.6987651968000002
002129.XSHE TCL中环 274.817117947
002131.XSHE 利欧股份 0.1445368035
002138.XSHE 顺络电子 28.7393180217
002142.XSHE 宁波银行 199.26910330419997
002145.XSHE 中核钛白 5.470408061599999
002146.XSHE 荣盛发展 0.0
002151.XSHE 北斗星通 0.2317616918
002152.XSHE 广电运通 2.8814351884000002
002153.XSHE 石基信息 44.719451513600006
002155.XSHE 湖南黄金 24.075446760000002
002156.XSHE 通富微电 6.782509812000001
002157.XSHE 正邦科技 0.0
002176.XSHE 江特电机 23.4327387429
002179.XSHE 中航光电 132.3097928256
002180.XSHE 纳思达 163.54335736800002
002183.XSHE 怡亚通 0.0
002185.XSHE 华天科技 5.469423002999999
002191.XSHE 劲嘉股份 0.10428834000000001
002192.XSHE 融捷股份 19.6863712173
002195.XSHE 二三四五 1.96415721
002202.XSHE 金风科技 13.6870057104
002203.XSHE 海亮股份 1.63969916
002216.XSHE 三全食品 0.5443792756
002223.XSHE 鱼跃医疗 47.834408488
002230.XSHE 科大讯飞 169.93593282880002
002236.XSHE 大华股份 79.200973719
002241.XSHE 歌尔股份 13.892309690000001
002242.XSHE 九阳股份 0.09414164480000001
002244.XSHE 滨江集团 24.8625005055
002245.XSHE 蔚蓝锂芯 0.04895676
002249.XSHE 大洋电机 1.2924057568
002250.XSHE 联化科技 23.717668538199998
002252.XSHE 上海莱士 12.793129157400001
002262.XSHE 恩华药业 22.039500204500005
002266.XSHE 浙富控股 0.0
002268.XSHE 电科网安 2.736917567
002271.XSHE 东方雨虹 124.38355746959999
002273.XSHE 水晶光电 6.917022695999999
002281.XSHE 光迅科技 0.6028372104
002294.XSHE 信立泰 15.071071308799999
002299.XSHE 圣农发展 39.869887275
002304.XSHE 洋河股份 377.07354807720003
002311.XSHE 海大集团 156.1438983983
002312.XSHE 川发龙蟒 0.9814527352000001
002320.XSHE 海峡股份 0.1095453375
002340.XSHE 格林美 11.857792094999997
002352.XSHE 顺丰控股 179.8819976304
002353.XSHE 杰瑞股份 38.178153768
002371.XSHE 北方华创 195.16208541700001
002372.XSHE 伟星新材 36.73599972110001
002373.XSHE 千方科技 0.43361455
002384.XSHE 东山精密 75.826955655
002385.XSHE 大北农 26.5169592787
002389.XSHE 航天彩虹 9.4655846376
002396.XSHE 星网锐捷 0.45924992000000003
002399.XSHE 海普瑞 0.1584287978
002402.XSHE 和而泰 12.565681333000002
002405.XSHE 四维图新 32.0178418725
002407.XSHE 多氟多 0.22363614
002408.XSHE 齐翔腾达 0.0
002409.XSHE 雅克科技 12.368108611999999
002410.XSHE 广联达 173.856038911
002414.XSHE 高德红外 0.4833297885000001
002415.XSHE 海康威视 378.25070285160007
002422.XSHE 科伦药业 37.281467122200006
002423.XSHE 中粮资本 0.0
002429.XSHE 兆驰股份 3.0145005114999996
002430.XSHE 杭氧股份 19.5737012224
002436.XSHE 兴森科技 12.706933579800001
002439.XSHE 启明星辰 23.2443285375
002444.XSHE 巨星科技 15.471883732799999
002456.XSHE 欧菲光 0.0
002459.XSHE 晶澳科技 342.96869101040005
002460.XSHE 赣锋锂业 118.60033650079998
002461.XSHE 珠江啤酒 0.36879968
002463.XSHE 沪电股份 70.1318028929
002465.XSHE 海格通信 11.490417225
002466.XSHE 天齐锂业 157.2666383488
002468.XSHE 申通快递 4.7690922239999995
002472.XSHE 双环传动 31.139000225500002
002475.XSHE 立讯精密 284.6834569775
002484.XSHE 江海股份 23.122597287199998
002487.XSHE 大金重工 17.5724251588
002493.XSHE 荣盛石化 78.78584743120001
002497.XSHE 雅化集团 11.276359275
002498.XSHE 汉缆股份 0.0
002500.XSHE 山西证券 0.0
002505.XSHE 鹏都农牧 0.0
002506.XSHE 协鑫集成 0.0
002507.XSHE 涪陵榨菜 4.1986293694
002508.XSHE 老板电器 8.8837297288
002511.XSHE 中顺洁柔 0.1961168
002531.XSHE 天顺风能 14.7301631028
002532.XSHE 天山铝业 15.3319567335
002541.XSHE 鸿路钢构 66.8945801601
002555.XSHE 三七互娱 55.688158025
002557.XSHE 洽洽食品 2.8119234562
002558.XSHE 巨人网络 5.1361980248000005
002563.XSHE 森马服饰 1.9725265644
002568.XSHE 百润股份 88.73773208760001
002572.XSHE 索菲亚 4.35475872
002585.XSHE 双星新材 0.0
002594.XSHE 比亚迪 342.53157994919997
002595.XSHE 豪迈科技 29.195236820999998
002597.XSHE 金禾实业 3.0520353152000004

002600.XSHE 领益智造 2.1054506658
002601.XSHE 龙佰集团 22.502224597599998
002602.XSHE 世纪华通 6.298716849600001
002603.XSHE 以岭药业 7.6757664273
002607.XSHE 中公教育 5.61704074
002608.XSHE 江苏国信 0.0
002610.XSHE 爱康科技 0.0
002617.XSHE 露笑科技 0.2764003872
002624.XSHE 完美世界 6.8217184604
002625.XSHE 光启技术 10.2302599392
002626.XSHE 金达威 0.6232285211999999
002643.XSHE 万润股份 20.7540412174
002648.XSHE 卫星化学 43.31489184
002653.XSHE 海思科 2.3819072163999997
002670.XSHE 国盛金控 0.0
002673.XSHE 西部证券 0.0
002683.XSHE 广东宏大 2.208829767
002690.XSHE 美亚光电 1.200290287
002701.XSHE 奥瑞金 0.9290533428000001
002705.XSHE 新宝股份 0.32171520000000003
002706.XSHE 良信股份 2.764903545
002709.XSHE 天赐材料 121.8744971412
002714.XSHE 牧原股份 125.04988258
002727.XSHE 一心堂 66.4035509184
002736.XSHE 国信证券 0.3159200444
002738.XSHE 中矿资源 45.69242139600001
002739.XSHE 万达电影 24.715204085
002745.XSHE 木林森 0.0
002747.XSHE 埃斯顿 10.146812090800001
002756.XSHE 永兴材料 56.742943443
002773.XSHE 康弘药业 1.0932424
002791.XSHE 坚朗五金 11.883651574300002
002797.XSHE 第一创业 0.0
002812.XSHE 恩捷股份 151.7618890326
002821.XSHE 凯莱英 105.14789790350001
002831.XSHE 裕同科技 15.0888348908
002841.XSHE 视源股份 42.8973145599
002850.XSHE 科达利 66.93639632680001
002867.XSHE 周大生 7.331109350400001
002901.XSHE 大博医疗 0.0301207
002906.XSHE 华阳集团 11.2101906504
002916.XSHE 深南电路 3.7350668656
002920.XSHE 德赛西威 23.802749229
002925.XSHE 盈趣科技 11.056537793599999
002926.XSHE 华西证券 0.0043619
002936.XSHE 郑州银行 0.0
002938.XSHE 鹏鼎控股 24.376939818000004
002939.XSHE 长城证券 2.1079940495
002945.XSHE 华林证券 0.0
002948.XSHE 青岛银行 0.0
002958.XSHE 青农商行 0.0
002966.XSHE 苏州银行 3.4467843048000004
002978.XSHE 安宁股份 0.06469815
002984.XSHE 森麒麟 30.2577527036
002985.XSHE 北摩高科 5.783091148800001
003022.XSHE 联泓新科 0.02726512
003035.XSHE 南网能源 4.627395088
003039.XSHE 顺控发展 0.0
003816.XSHE 中国广核 3.00416676
300001.XSHE 特锐德 0.192569266
300003.XSHE 乐普医疗 29.848944413599998
300009.XSHE 安科生物 2.2302343180000004
300012.XSHE 华测检测 82.17155179
300014.XSHE 亿纬锂能 366.33887790299997
300015.XSHE 爱尔眼科 478.0388349512
300017.XSHE 网宿科技 2.80313654
300024.XSHE 机器人 0.01188228
300026.XSHE 红日药业 12.310042987500001
300033.XSHE 同花顺 138.67704215999998
300034.XSHE 钢研高纳 31.4001827028
300037.XSHE 新宙邦 87.87263279830002
300054.XSHE 鼎龙股份 44.49795546
300058.XSHE 蓝色光标 19.4163041696
300059.XSHE 东方财富 397.5250102237
300068.XSHE 南都电源 44.69624546400001
300070.XSHE 碧水源 0.0002525
300073.XSHE 当升科技 41.1755562528
300088.XSHE 长信科技 0.19356713
300115.XSHE 长盈精密 4.782306919
300118.XSHE 东方日升 29.4216551096
300122.XSHE 智飞生物 169.50105009509997
300124.XSHE 汇川技术 241.47724511
300136.XSHE 信维通信 0.6683099016
300142.XSHE 沃森生物 58.4287636711
300144.XSHE 宋城演艺 58.4165149315
300146.XSHE 汤臣倍健 23.6207042295
300171.XSHE 东富龙 0.59085536
300182.XSHE 捷成股份 4.0252468696
300207.XSHE 欣旺达 38.614844419200004
300223.XSHE 北京君正 16.565982217200002
300244.XSHE 迪安诊断 12.4135719885
300251.XSHE 光线传媒 6.7778860631999995
300253.XSHE 卫宁健康 54.4617216053
300257.XSHE 开山股份 1.510940676
300274.XSHE 阳光电源 485.7911076914
300285.XSHE 国瓷材料 38.418027642800006
300294.XSHE 博雅生物 7.4248304802
300296.XSHE 利亚德 0.28979955
300298.XSHE 三诺生物 42.320719282
300308.XSHE 中际旭创 101.31707552300001
300316.XSHE 晶盛机电 122.43469773540001
300346.XSHE 南大光电 0.099165184
300347.XSHE 泰格医药 224.85642153690003
300357.XSHE 我武生物 11.890123952000001
300363.XSHE 博腾股份 1.5523014360999998
300373.XSHE 扬杰科技 4.9280473
300376.XSHE 易事特 0.0
300383.XSHE 光环新网 0.866944431
300390.XSHE 天华新能 13.4534060306
300395.XSHE 菲利华 52.5936862895
300408.XSHE 三环集团 80.50790110999999
300413.XSHE 芒果超媒 51.48707437999999
300418.XSHE 昆仑万维 38.8064687568
300432.XSHE 富临精工 0.14806674
300433.XSHE 蓝思科技 1.5719728024000001
300438.XSHE 鹏辉能源 31.1871420615
300450.XSHE 先导智能 36.5333570624
300454.XSHE 深信服 155.1761689968
300457.XSHE 赢合科技 4.2913719072
300458.XSHE 全志科技 0.2906631
300459.XSHE 汤姆猫 9.4435605825
300474.XSHE 景嘉微 22.47369564
300476.XSHE 胜宏科技 1.7632973496000002
300482.XSHE 万孚生物 0.0932876904
300487.XSHE 蓝晓科技 54.02574702849999
300496.XSHE 中科创达 86.3601562175
300498.XSHE 温氏股份 141.4223034851
300502.XSHE 新易盛 8.11240973
300529.XSHE 健帆生物 8.196993555999999
300558.XSHE 贝达药业 14.6334505512
300567.XSHE 精测电子 38.672994115
300568.XSHE 星源材质 41.0442804564
300595.XSHE 欧普康视 13.77426852
300601.XSHE 康泰生物 1.9674799284
300604.XSHE 长川科技 47.9484457608
300618.XSHE 寒锐钴业 0.01826928
300623.XSHE 捷捷微电 0.89962813
300628.XSHE 亿联网络 75.0377431683
300630.XSHE 普利制药 2.6582688
300633.XSHE 开立医疗 55.758257625599995
300661.XSHE 圣邦股份 176.583477728
300666.XSHE 江丰电子 20.3283012555
300671.XSHE 富满微 0.0005495
300672.XSHE 国科微 0.73865744
300676.XSHE 华大基因 16.25717556
300677.XSHE 英科医疗 13.678380994800001
300682.XSHE 朗新科技 13.506566523000002
300699.XSHE 光威复材 12.8009676852
300724.XSHE 捷佳伟创 63.65606660999999
300725.XSHE 药石科技 8.1447069312
300726.XSHE 宏达电子 0.36227148000000003
300741.XSHE 华宝股份 0.0364743093
300747.XSHE 锐科激光 7.975871431199999
300748.XSHE 金力永磁 4.090433694200001
300750.XSHE 宁德时代 1718.1323261080001
300751.XSHE 迈为股份 26.0071792
300759.XSHE 康龙化成 95.1347086425
300760.XSHE 迈瑞医疗 568.8665668517999
300761.XSHE 立华股份 13.714086456100002
300763.XSHE 锦浪科技 111.67895807720001
300769.XSHE 德方纳米 33.910688196
300773.XSHE 拉卡拉 2.4803382642000003
300775.XSHE 三角防务 30.314776639
300776.XSHE 帝尔激光 4.400866940399999
300777.XSHE 中简科技 18.853711847999996
300782.XSHE 卓胜微 65.0124974
300803.XSHE 指南针 3.227900364
300821.XSHE 东岳硅材 0.0
300832.XSHE 新产业 14.049931768799999
300841.XSHE 康华生物 13.813575367999997
300850.XSHE 新强联 0.133588
300861.XSHE 美畅股份 1.6380989875999998
300866.XSHE 安克创新 0.7665718175999999
300888.XSHE 稳健医疗 0.9369431640000001
300894.XSHE 火星人 0.0
300896.XSHE 爱美客 191.40653985
300919.XSHE 中伟股份 10.5471239928
300957.XSHE 贝泰妮 17.971463992900002
300973.XSHE 立高食品 16.696640092800003
300979.XSHE 华利集团 8.722880836800002
300999.XSHE 金龙鱼 1.938403536
301029.XSHE 怡合达 0.2450765312
301035.XSHE 润丰股份 18.2308106592
301047.XSHE 义翘神州 0.01675212
301071.XSHE 力量钻石 0.0722792736
301177.XSHE 迪阿股份 0.031902
301200.XSHE 大族数控 0.0
301219.XSHE 腾远钴业 0.0
600000.XSHG 浦发银行 15.918782949
600004.XSHG 白云机场 20.5857229803
600008.XSHG 首创环保 3.198842955
600009.XSHG 上海机场 44.65286054530001
600010.XSHG 包钢股份 6.383174093099999
600011.XSHG 华能国际 72.61659724489999
600015.XSHG 华夏银行 2.4239114408
600016.XSHG 民生银行 12.911094631500001
600018.XSHG 上港集团 18.322260840000002
600019.XSHG 宝钢股份 13.397725411200001
600021.XSHG 上海电力 13.568618819100001
600022.XSHG 山东钢铁 0.38714814000000003
600023.XSHG 浙能电力 0.0
600025.XSHG 华能水电 14.0612330593
600026.XSHG 中远海能 41.7550877172
600027.XSHG 华电国际 29.020598280600005
600028.XSHG 中国石化 27.481117057600002
600029.XSHG 南方航空 79.09342137870001
600030.XSHG 中信证券 224.02744750079998
600031.XSHG 三一重工 66.635796736
600032.XSHG 浙江新能 0.0
600036.XSHG 招商银行 379.8420302492
600037.XSHG 歌华有线 0.0889052458
600038.XSHG 中直股份 15.908440685799999
600039.XSHG 四川路桥 12.088355088
600048.XSHG 保利发展 272.4436158507
600050.XSHG 中国联通 22.8719356144
600056.XSHG 中国医药 1.0976e-05
600060.XSHG 海信视像 60.7642746543
600061.XSHG 国投资本 0.0
600062.XSHG 华润双鹤 0.01786064
600064.XSHG 南京高科 0.0
600066.XSHG 宇通客车 13.7613313791
600079.XSHG 人福医药 102.1759053224
600085.XSHG 同仁堂 157.72294784879998
600089.XSHG 特变电工 37.9761056935
600095.XSHG 湘财股份 1.5198676532
600096.XSHG 云天化 0.6732707064
600098.XSHG 广州发展 0.73531629
600100.XSHG 同方股份 0.6938503968
600104.XSHG 上汽集团 15.395438426400002
600109.XSHG 国金证券 0.11649792
600110.XSHG 诺德股份 0.0
600111.XSHG 北方稀土 11.785191648199998
600115.XSHG 中国东航 59.2976916544
600116.XSHG 三峡水利 0.0
600118.XSHG 中国卫星 6.1627949916
600120.XSHG 浙江东方 0.0
600126.XSHG 杭钢股份 0.0
600131.XSHG 国网信通 16.371003008600002
600132.XSHG 重庆啤酒 41.499435
600141.XSHG 兴发集团 2.5240062855
600143.XSHG 金发科技 0.77428434
600150.XSHG 中国船舶 98.99868583800001
600153.XSHG 建发股份 34.4826014672
600155.XSHG 华创阳安 1.4019309696000002
600157.XSHG 永泰能源 12.074581811600002
600160.XSHG 巨化股份 20.027842827199997
600161.XSHG 天坛生物 11.991696130000001
600166.XSHG 福田汽车 14.967516303799998
600167.XSHG 联美控股 0.0
600170.XSHG 上海建工 0.34530961920000003
600171.XSHG 上海贝岭 1.9229451519999998
600176.XSHG 中国巨石 20.480419263
600177.XSHG 雅戈尔 2.4238072616
600183.XSHG 生益科技 1.9897155304
600188.XSHG 兖矿能源 60.747657158500004
600195.XSHG 中牧股份 27.7861123524
600196.XSHG 复星医药 24.254607910700003
600206.XSHG 有研新材 0.65740798
600208.XSHG 新湖中宝 0.0
600216.XSHG 浙江医药 4.6632284956
600219.XSHG 南山铝业 22.8688445376
600233.XSHG 圆通速递 34.944565707200006
600236.XSHG 桂冠电力 0.5090248944
600246.XSHG 万通发展 0.01401402
600256.XSHG 广汇能源 120.13773423
600258.XSHG 首旅酒店 40.259441412
600259.XSHG 广晟有色 0.26262369
600267.XSHG 海正药业 0.0

600271.XSHG 航天信息 2.1256153816
600273.XSHG 嘉化能源 0.0
600276.XSHG 恒瑞医药 322.3741689904
600282.XSHG 南钢股份 10.4173648787
600295.XSHG 鄂尔多斯 0.0264941
600297.XSHG 广汇汽车 0.1020978
600298.XSHG 安琪酵母 22.6900315675
600299.XSHG 安迪苏 0.0
600309.XSHG 万华化学 303.7419395448
600315.XSHG 上海家化 4.9815486
600316.XSHG 洪都航空 7.214574369599999
600323.XSHG 瀚蓝环境 8.6198572845
600325.XSHG 华发股份 47.1602763016
600329.XSHG 达仁堂 14.7010011414
600330.XSHG 天通股份 1.4642474568000001
600332.XSHG 白云山 5.5317404788
600338.XSHG 西藏珠峰 13.508088879999997
600339.XSHG 中油工程 0.0
600340.XSHG 华夏幸福 0.0
600346.XSHG 恒力石化 22.729830552000003
600348.XSHG 华阳股份 11.449216314000001
600350.XSHG 山东高速 6.1182100836
600352.XSHG 浙江龙盛 5.800200942900001
600362.XSHG 江西铜业 0.1668734359
600369.XSHG 西南证券 0.0
600372.XSHG 中航电子 61.1463526224
600373.XSHG 中文传媒 3.8306957919999998
600376.XSHG 首开股份 0.40129824000000003
600377.XSHG 宁沪高速 0.40866336200000003
600378.XSHG 昊华科技 43.3514721795
600380.XSHG 健康元 4.37707584
600383.XSHG 金地集团 28.014744072
600390.XSHG 五矿资本 0.11902891
600392.XSHG 盛和资源 1.3601475250000001
600395.XSHG 盘江股份 5.1261400587
600398.XSHG 海澜之家 6.322953561599999
600399.XSHG 抚顺特钢 47.562631999500006
600406.XSHG 国电南瑞 24.975342605100003
600409.XSHG 三友化工 0.16166588
600415.XSHG 小商品城 2.3375523396
600416.XSHG 湘电股份 21.153393227900004
600418.XSHG 江淮汽车 12.556385410499997
600426.XSHG 华鲁恒升 209.8265397375
600435.XSHG 北方导航 1.2483622138
600436.XSHG 片仔癀 112.37122419180001
600438.XSHG 通威股份 144.721997967
600456.XSHG 宝钛股份 0.41668276
600460.XSHG 士兰微 33.502669258900006
600481.XSHG 双良节能 18.3960324909
600482.XSHG 中国动力 1.035986495
600483.XSHG 福能股份 8.9453954724
600486.XSHG 扬农化工 55.5041332923
600487.XSHG 亨通光电 34.1246863
600489.XSHG 中金黄金 60.8009417262
600497.XSHG 驰宏锌锗 15.164859427200001
600498.XSHG 烽火通信 1.893116176
600499.XSHG 科达制造 5.6095640874
600500.XSHG 中化国际 0.21133944000000002
600507.XSHG 方大特钢 0.0
600511.XSHG 国药股份 24.96754558
600516.XSHG 方大炭素 0.93267944
600517.XSHG 国网英大 0.1186108039
600519.XSHG 贵州茅台 2232.4778476
600521.XSHG 华海药业 33.6970262326
600522.XSHG 中天科技 32.0198586927
600528.XSHG 中铁工业 0.37339104
600529.XSHG 山东药玻 3.3384354153999998
600535.XSHG 天士力 1.417036061
600536.XSHG 中国软件 52.7927373355
600546.XSHG 山煤国际 37.6290858204
600547.XSHG 山东黄金 64.5812330996
600549.XSHG 厦门钨业 2.668178132
600556.XSHG 天下秀 0.151885
600559.XSHG 老白干酒 119.7719566754
600562.XSHG 国睿科技 2.9643775296000006
600563.XSHG 法拉电子 37.7174959332
600566.XSHG 济川药业 6.046761104
600567.XSHG 山鹰国际 0.25968839
600570.XSHG 恒生电子 197.40590820239998
600578.XSHG 京能电力 0.87003045
600580.XSHG 卧龙电驱 0.5676149340000001
600582.XSHG 天地科技 5.3126961056
600583.XSHG 海油工程 9.289821905
600584.XSHG 长电科技 49.0593608395
600585.XSHG 海螺水泥 54.914794755
600588.XSHG 用友网络 37.598141388
600596.XSHG 新安股份 0.03502329600000001
600597.XSHG 光明乳业 0.8350279700000001
600598.XSHG 北大荒 1.1420841388
600600.XSHG 青岛啤酒 165.787554906
600606.XSHG 绿地控股 5.074849728
600612.XSHG 老凤祥 10.1474820363
600621.XSHG 华鑫股份 2.3160000000000002e-05
600623.XSHG 华谊集团 0.0
600637.XSHG 东方明珠 2.6417683798
600641.XSHG 万业企业 2.7741458772000005
600642.XSHG 申能股份 2.4135582
600648.XSHG 外高桥 2.474e-05
600655.XSHG 豫园股份 0.0
600660.XSHG 福耀玻璃 52.4505514016
600663.XSHG 陆家嘴 4.0647544767
600667.XSHG 太极实业 0.42667968
600673.XSHG 东阳光 25.258980274499997
600674.XSHG 川投能源 16.0691457126
600682.XSHG 南京新百 0.0
600685.XSHG 中船防务 10.2118699676
600688.XSHG 上海石化 0.053133105
600690.XSHG 海尔智家 148.77985673879996
600699.XSHG 均胜电子 3.221618653
600702.XSHG 舍得酒业 192.81659271
600703.XSHG 三安光电 147.7718363973
600704.XSHG 物产中大 0.21740018300000002
600705.XSHG 中航产融 0.00164
600707.XSHG 彩虹股份 0.0
600711.XSHG 盛屯矿业 0.00187616
600717.XSHG 天津港 0.0
600718.XSHG 东软集团 1.9069201554000001
600732.XSHG 爱旭股份 17.6722943012
600733.XSHG 北汽蓝谷 2.0203955832
600737.XSHG 中粮糖业 1.57484048
600739.XSHG 辽宁成大 0.522253683
600740.XSHG 山西焦化 0.0
600741.XSHG 华域汽车 24.684711762600003
600745.XSHG 闻泰科技 36.653441175
600746.XSHG 江苏索普 0.0
600754.XSHG 锦江酒店 116.66640438270001
600755.XSHG 厦门国贸 3.1484391392
600760.XSHG 中航沈飞 110.51735668839999
600763.XSHG 通策医疗 80.6097541376
600764.XSHG 中国海防 0.39475344
600765.XSHG 中航重机 81.78834487900001
600777.XSHG 新潮能源 0.00087348
600779.XSHG 水井坊 3.3145297928999997
600782.XSHG 新钢股份 2.16224274
600787.XSHG 中储股份 0.024816
600795.XSHG 国电电力 6.2251277
600801.XSHG 华新水泥 6.4985246025
600803.XSHG 新奥股份 23.7472228005
600808.XSHG 马钢股份 0.89206848
600809.XSHG 山西汾酒 593.563165716
600820.XSHG 隧道股份 2.919398925
600827.XSHG 百联股份 0.5278453
600837.XSHG 海通证券 63.8740204298
600839.XSHG 四川长虹 1.53234669
600845.XSHG 宝信软件 96.065200524
600848.XSHG 上海临港 4.2950595573
600859.XSHG 王府井 36.0654582939
600862.XSHG 中航高科 61.41075296780001
600863.XSHG 内蒙华电 10.1191618624
600867.XSHG 通化东宝 5.635611488000001
600871.XSHG 石化油服 1.6903362
600872.XSHG 中炬高新 25.842416068000002
600873.XSHG 梅花生物 13.187118747000001
600875.XSHG 东方电气 17.471043518400002
600879.XSHG 航天电子 3.5827961191999997
600882.XSHG 妙可蓝多 0.21386080000000002
600884.XSHG 杉杉股份 0.01611005
600885.XSHG 宏发股份 27.4093097924
600886.XSHG 国投电力 14.879736909000002
600887.XSHG 伊利股份 225.74644572479997
600893.XSHG 航发动力 81.45567981299999
600895.XSHG 张江高科 1.8762407755000001
600900.XSHG 长江电力 133.998063
600901.XSHG 江苏金租 1.0394869315
600905.XSHG 三峡能源 3.5204419268000007
600906.XSHG 财达证券 0.0
600909.XSHG 华安证券 0.00104112
600916.XSHG 中国黄金 0.08220232
600918.XSHG 中泰证券 0.0109612
600919.XSHG 江苏银行 62.83198335960001
600926.XSHG 杭州银行 52.2559428894
600927.XSHG 永安期货 0.0
600928.XSHG 西安银行 0.0
600938.XSHG 中国海油 60.5842446768
600941.XSHG 中国移动 134.3010314622
600955.XSHG 维远股份 0.0
600956.XSHG 新天绿能 0.20290435
600958.XSHG 东方证券 42.8711258448
600959.XSHG 江苏有线 0.30727997
600967.XSHG 内蒙一机 2.474368519
600968.XSHG 海油发展 10.9288146
600970.XSHG 中材国际 3.2336384678000005
600977.XSHG 中国电影 1.6320652558000002
600985.XSHG 淮北矿业 15.4925721492
600988.XSHG 赤峰黄金 77.18892602849999
600989.XSHG 宝丰能源 17.8788084975
600998.XSHG 九州通 2.9739569975999998
600999.XSHG 招商证券 42.491552145700005
601000.XSHG 唐山港 9.647150338
601001.XSHG 晋控煤业 3.1251031398
601005.XSHG 重庆钢铁 0.4327475114
601006.XSHG 大秦铁路 17.3750604323
601009.XSHG 南京银行 22.733206092800003
601012.XSHG 隆基绿能 407.3484503889
601016.XSHG 节能风电 0.12105476100000001
601018.XSHG 宁波港 0.0
601021.XSHG 春秋航空 112.9833221366
601058.XSHG 赛轮轮胎 123.98862253310001
601066.XSHG 中信建投 2.3174933056
601077.XSHG 渝农商行 0.2736519352
601088.XSHG 中国神华 68.96010027960001
601098.XSHG 中南传媒 10.0352523312
601099.XSHG 太平洋 0.0
601100.XSHG 恒立液压 69.7411889034
601106.XSHG 中国一重 0.0
601108.XSHG 财通证券 2.8433257278999995
601111.XSHG 中国国航 120.5772110688
601117.XSHG 中国化学 31.023112940799994
601118.XSHG 海南橡胶 0.0
601127.XSHG 赛力斯 50.2015401595
601128.XSHG 常熟银行 26.7056108375
601138.XSHG 工业富联 42.350445248999996
601139.XSHG 深圳燃气 0.035205520000000004
601155.XSHG 新城控股 14.8729297668
601156.XSHG 东航物流 0.021537360000000002
601158.XSHG 重庆水务 0.0
601162.XSHG 天风证券 0.0
601166.XSHG 兴业银行 146.80554630870003
601168.XSHG 西部矿业 6.7808785856
601169.XSHG 北京银行 2.8170790560000003
601179.XSHG 中国西电 0.12283425
601186.XSHG 中国铁建 17.0581962853
601187.XSHG 厦门银行 0.044766
601198.XSHG 东兴证券 0.0
601211.XSHG 国泰君安 47.449724593199996
601212.XSHG 白银有色 0.0
601216.XSHG 君正集团 0.009984680000000001
601222.XSHG 林洋能源 4.673174528400001
601225.XSHG 陕西煤业 108.95646605939999
601228.XSHG 广州港 0.0
601229.XSHG 上海银行 0.2913043622
601231.XSHG 环旭电子 6.189852353399999
601233.XSHG 桐昆股份 20.556133934
601236.XSHG 红塔证券 0.575245595
601238.XSHG 广汽集团 6.2165010994
601288.XSHG 农业银行 24.812296481799997
601298.XSHG 青岛港 1.0778236
601311.XSHG 骆驼股份 3.0579163460000003
601318.XSHG 中国平安 309.043002648
601319.XSHG 中国人保 6.311008704
601328.XSHG 交通银行 33.664760431400005
601333.XSHG 广深铁路 0.19151788
601336.XSHG 新华保险 8.23560634
601360.XSHG 三六零 69.56453912299999
601375.XSHG 中原证券 1.488e-05
601377.XSHG 兴业证券 36.1487300076
601390.XSHG 中国中铁 38.7516625392
601398.XSHG 工商银行 61.87003974120001
601399.XSHG 国机重装 0.0
601456.XSHG 国联证券 4.659704841
601519.XSHG 大智慧 0.01524557
601555.XSHG 东吴证券 1.1583964769000001
601567.XSHG 三星医疗 21.3673305873
601568.XSHG 北元集团 0.139329534
601577.XSHG 长沙银行 16.9486694363
601598.XSHG 中国外运 0.1022528
601600.XSHG 中国铝业 15.8660722992
601601.XSHG 中国太保 79.1396972352
601607.XSHG 上海医药 7.8163220121000005
601608.XSHG 中信重工 0.0
601611.XSHG 中国核建 0.0
601615.XSHG 明阳智能 17.6705958092
601618.XSHG 中国中冶 6.096650547
601628.XSHG 中国人寿 30.136727257199997
601633.XSHG 长城汽车 39.796515479700005
601636.XSHG 旗滨集团 11.8409436992
601658.XSHG 邮储银行 36.544444255500004
601665.XSHG 齐鲁银行 0.0213268
601666.XSHG 平煤股份 2.8672090775
601668.XSHG 中国建筑 135.692434514

601669.XSHG 中国电建 14.800875901
601677.XSHG 明泰铝业 21.984599286799998
601688.XSHG 华泰证券 69.0371580375
601689.XSHG 拓普集团 86.74634884720001
601696.XSHG 中银证券 0.00335088
601698.XSHG 中国卫通 0.8953855731999998
601699.XSHG 潞安环能 54.537942772600005
601717.XSHG 郑煤机 5.6630499628
601718.XSHG 际华集团 0.0
601727.XSHG 上海电气 2.1842320188
601728.XSHG 中国电信 73.3757961102
601766.XSHG 中国中车 16.0060560768
601777.XSHG 力帆科技 0.0
601778.XSHG 晶科科技 0.4540856589999999
601788.XSHG 光大证券 2.5059531288
601799.XSHG 星宇股份 38.077864780999995
601800.XSHG 中国交建 16.489981622400002
601808.XSHG 中海油服 2.2792185000000003
601816.XSHG 京沪高铁 23.852505666600003
601818.XSHG 光大银行 6.698329386
601825.XSHG 沪农商行 0.79377408
601828.XSHG 美凯龙 0.01113024
601838.XSHG 成都银行 72.5063422884
601857.XSHG 中国石油 18.3906699136
601865.XSHG 福莱特 57.1642440499
601866.XSHG 中远海发 0.0
601868.XSHG 中国能建 5.1756242031
601869.XSHG 长飞光纤 0.44298
601872.XSHG 招商轮船 39.4576651521
601877.XSHG 正泰电器 7.578260885899999
601878.XSHG 浙商证券 1.4877898339000002
601880.XSHG 辽港股份 0.0
601881.XSHG 中国银河 2.1294369135
601888.XSHG 中国中免 230.9485734612
601898.XSHG 中煤能源 18.916846408
601899.XSHG 紫金矿业 335.4165027654
601901.XSHG 方正证券 0.02873034
601908.XSHG 京运通 0.7899929576000001
601916.XSHG 浙商银行 1.7179291558000003
601919.XSHG 中远海控 10.8009956915
601928.XSHG 凤凰传媒 12.8175565397
601933.XSHG 永辉超市 0.0
601939.XSHG 建设银行 11.0585366694
601952.XSHG 苏垦农发 0.0
601958.XSHG 金钼股份 4.7536919848000005
601966.XSHG 玲珑轮胎 11.5118401512
601969.XSHG 海南矿业 0.0
601985.XSHG 中国核电 42.712702560000004
601988.XSHG 中国银行 2.5167574978
601989.XSHG 中国重工 12.8847176766
601990.XSHG 南京证券 0.05519838
601991.XSHG 大唐发电 9.145153726500002
601992.XSHG 金隅集团 0.710588641
601995.XSHG 中金公司 0.259170192
601997.XSHG 贵阳银行 0.015944838
601998.XSHG 中信银行 0.6506235231
603000.XSHG 人民网 0.2727869009
603005.XSHG 晶方科技 0.54296
603019.XSHG 中科曙光 55.62544505080001
603025.XSHG 大豪科技 0.0
603026.XSHG 胜华新材 1.9168294518000002
603027.XSHG 千禾味业 10.558711863000001
603043.XSHG 广州酒家 0.9255916956000001
603056.XSHG 德邦股份 1.1592053368000002
603077.XSHG 和邦生物 0.09167041000000001
603087.XSHG 甘李药业 3.197414202
603098.XSHG 森特股份 13.801882535999999
603127.XSHG 昭衍新药 8.4228254264
603129.XSHG 春风动力 30.346674042300002
603156.XSHG 养元饮品 5.075095181599999
603160.XSHG 汇顶科技 2.0245221494
603185.XSHG 上机数控 27.9619514806
603195.XSHG 公牛集团 2.9900832852
603198.XSHG 迎驾贡酒 25.5210866217
603218.XSHG 日月股份 16.887561471999998
603225.XSHG 新凤鸣 6.010137895999999
603228.XSHG 景旺电子 31.476500736000006
603233.XSHG 大参林 5.532448737000002
603236.XSHG 移远通信 4.6240132314
603259.XSHG 药明康德 621.1354716
603260.XSHG 合盛硅业 0.5378616348
603267.XSHG 鸿远电子 34.8069700992
603288.XSHG 海天味业 29.660956076600005
603290.XSHG 斯达半导 11.076242033000002
603298.XSHG 杭叉集团 4.317789048
603305.XSHG 旭升集团 39.663327861
603317.XSHG 天味食品 0.07690176
603338.XSHG 浙江鼎力 32.5723580382
603345.XSHG 安井食品 104.1762404106
603369.XSHG 今世缘 128.81604456550002
603379.XSHG 三美股份 6.9636892959
603392.XSHG 万泰生物 20.7963752555
603444.XSHG 吉比特 38.0572096692
603456.XSHG 九洲药业 70.7253150976
603486.XSHG 科沃斯 26.722842033999996
603489.XSHG 八方股份 2.9906462456000003
603501.XSHG 韦尔股份 68.39635954100001
603517.XSHG 绝味食品 16.479779887999996
603529.XSHG 爱玛科技 21.414774629500002
603565.XSHG 中谷物流 11.424580580999999
603568.XSHG 伟明环保 13.805784864000001
603583.XSHG 捷昌驱动 1.2306385784
603589.XSHG 口子窖 27.001273023999996
603596.XSHG 伯特利 80.51087547959999
603605.XSHG 珀莱雅 45.434265968999995
603606.XSHG 东方电缆 31.8071724017
603613.XSHG 国联股份 110.86851965700004
603638.XSHG 艾迪精密 0.22210902000000002
603650.XSHG 彤程新材 6.8723935560000005
603658.XSHG 安图生物 8.3773505002
603659.XSHG 璞泰来 88.87515674309999
603678.XSHG 火炬电子 42.629188711699996
603688.XSHG 石英股份 71.6029575912
603707.XSHG 健友股份 25.463448262
603712.XSHG 七一二 16.0128774044
603713.XSHG 密尔克卫 3.006891087299999
603733.XSHG 仙鹤股份 0.08111334
603737.XSHG 三棵树 29.326111968999996
603786.XSHG 科博达 9.1302284356
603799.XSHG 华友钴业 182.25817610000001
603806.XSHG 福斯特 90.8322123375
603816.XSHG 顾家家居 38.1570315048
603826.XSHG 坤彩科技 0.0019152
603833.XSHG 欧派家居 65.25939063599999
603858.XSHG 步长制药 0.0
603866.XSHG 桃李面包 1.3499650872
603868.XSHG 飞科电器 19.547561950800006
603882.XSHG 金域医学 107.368778514
603883.XSHG 老百姓 38.0537986482
603885.XSHG 吉祥航空 107.7973060244
603893.XSHG 瑞芯微 40.1109614652
603899.XSHG 晨光股份 15.874730165999997
603919.XSHG 金徽酒 0.0086814
603927.XSHG 中科软 8.042010718
603939.XSHG 益丰药房 18.2908863452
603986.XSHG 兆易创新 195.59866916000001
603993.XSHG 洛阳钼业 61.05206370830001
605111.XSHG 新洁能 3.3721891032
605117.XSHG 德业股份 95.010911442
605358.XSHG 立昂微 11.3422554864
605499.XSHG 东鹏饮料 22.4224647162
605589.XSHG 圣泉集团 1.823645896
688005.XSHG 容百科技 22.508970767999994
688006.XSHG 杭可科技 8.623388480000003
688008.XSHG 澜起科技 169.4332154162
688009.XSHG 中国通号 1.4587900732000003
688012.XSHG 中微公司 240.709192911
688017.XSHG 绿的谐波 6.2843557329
688036.XSHG 传音控股 49.664382724
688050.XSHG 爱博医疗 21.4717088304
688063.XSHG 派能科技 29.6453209642
688065.XSHG 凯赛生物 0.7910142075000001
688099.XSHG 晶晨股份 47.346246383
688111.XSHG 金山办公 441.39429609
688122.XSHG 西部超导 97.1746734815
688126.XSHG 沪硅产业 51.903297650500015
688139.XSHG 海尔生物 2.9674807050000003
688161.XSHG 威高骨科 2.1364923762
688169.XSHG 石头科技 35.1741375
688180.XSHG 君实生物 0.8976917736
688187.XSHG 时代电气 2.58120632
688188.XSHG 柏楚电子 22.563040383000004
688200.XSHG 华峰测控 20.4895178
688202.XSHG 美迪西 4.4644385944
688256.XSHG 寒武纪 123.57864210550001
688276.XSHG 百克生物 0.6257147629
688301.XSHG 奕瑞科技 40.285135457699994
688303.XSHG 大全能源 3.3474129816
688363.XSHG 华熙生物 7.41702906
688385.XSHG 复旦微电 20.084545863599995
688390.XSHG 固德威 77.82043577350001
688396.XSHG 华润微 30.147445497600007
688425.XSHG 铁建重工 4.2883315932
688516.XSHG 奥特维 33.8277313221
688520.XSHG 神州细胞 0.05521752199999999
688521.XSHG 芯原股份 46.05622891200001
688536.XSHG 思瑞浦 60.17667862700001
688538.XSHG 和辉光电 0.0413049115
688561.XSHG 奇安信 13.841874667999999
688567.XSHG 孚能科技 0.0065772
688598.XSHG 金博股份 19.394107884
688599.XSHG 天合光能 278.0411492956
688690.XSHG 纳微科技 0.41175280000000003
688707.XSHG 振华新材 0.05457055119999999
688728.XSHG 格科微 0.0
688772.XSHG 珠海冠宇 1.3528619664
688777.XSHG 中控技术 83.2110711305
688778.XSHG 厦钨新能 0.046811833899999995
688779.XSHG 长远锂科 0.09644041599999997
688819.XSHG 天能股份 0.09937712639999999
688981.XSHG 中芯国际 225.6766432379
689009.XSHG 九号公司 29.199740398400003

In [14]:
fportfolio.head()

000001.XSHE    98.392444
000002.XSHE    91.696656
000009.XSHE     0.117066
000012.XSHE     0.605041
000021.XSHE     2.364492
dtype: float64

In [15]:
fweight = 100 * fportfolio / fportfolio.sum()
fweight = fweight.sort_values(ascending=False)
fweight.head()

600519.XSHG    5.544621
300750.XSHE    4.267183
000858.XSHE    2.919360
000568.XSHE    2.805544
603259.XSHG    1.542663
dtype: float64

In [16]:
index_weight = get_index_weights(index, dt_end)
index_weight = index_weight.sort_values(by='weight', ascending=False)
index_weight[:10]

                   date  weight display_name
code
600519.XSHG  2023-03-31  3.8417         贵州茅台
300750.XSHE  2023-03-31  1.9123         宁德时代
601318.XSHG  2023-03-31  1.6312         中国平安
600036.XSHG  2023-03-31  1.5410         招商银行
000858.XSHE  2023-03-31  1.3252          五粮液
601166.XSHG  2023-03-31  1.0182         兴业银行
000333.XSHE  2023-03-31  0.9669         美的集团
601012.XSHG  2023-03-31  0.8570         隆基绿能
002594.XSHE  2023-03-31  0.8077          比亚迪
600900.XSHG  2023-03-31  0.7767         长江电力

In [17]:
fdelta = pd.Series()
for s in index_weight.index:
    if s in fweight.index:
        fdelta[s] = fweight[s] - index_weight.weight[s]
fdelta = fdelta.sort_values(ascending=False)

In [18]:
# 最受欢迎的个股
the_best_delta = fdelta[fdelta > 0].sort_values(ascending=False)
the_best_list = the_best_delta.index.tolist()
the_best = index_weight.loc[the_best_list]
the_best['delta'] = the_best_delta
print(len(the_best))
the_best.head(15)

262

                   date  weight display_name     delta
code
300750.XSHE  2023-03-31  1.9123         宁德时代  2.354883
000568.XSHE  2023-03-31  0.7014         泸州老窖  2.104144
600519.XSHG  2023-03-31  3.8417         贵州茅台  1.702921
000858.XSHE  2023-03-31  1.3252          五粮液  1.594160
600809.XSHG  2023-03-31  0.3993         山西汾酒  1.074884
603259.XSHG  2023-03-31  0.5668         药明康德  0.975863
300760.XSHE  2023-03-31  0.5316         迈瑞医疗  0.881247
300015.XSHE  2023-03-31  0.3438         爱尔眼科  0.843466
300274.XSHE  2023-03-31  0.3868         阳光电源  0.819719
688111.XSHG  2023-03-31  0.3112         金山办公  0.785055
000596.XSHE  2023-03-31  0.1570         古井贡酒  0.723261
002459.XSHE  2023-03-31  0.2253         晶澳科技  0.626503
300014.XSHE  2023-03-31  0.3216         亿纬锂能  0.588246
002304.XSHE  2023-03-31  0.3664         洋河股份  0.570106
688599.XSHG  2023-03-31  0.1927         天合光能  0.497848

In [19]:
# 最被抛弃的个股
the_worst_delta = fdelta[fdelta < 0].sort_values(ascending=True)
the_worst_list = the_worst_delta.index.tolist()
the_worst = index_weight.loc[the_worst_list]
the_worst['delta'] = the_worst_delta
print(len(the_worst))
the_worst.head(15)

738

                   date  weight display_name     delta
code
601318.XSHG  2023-03-31  1.6312         中国平安 -0.863655
601166.XSHG  2023-03-31  1.0182         兴业银行 -0.653591
600036.XSHG  2023-03-31  1.5410         招商银行 -0.597618
600900.XSHG  2023-03-31  0.7767         长江电力 -0.443900
000333.XSHE  2023-03-31  0.9669         美的集团 -0.432665
601398.XSHG  2023-03-31  0.5801         工商银行 -0.426438
000725.XSHE  2023-03-31  0.5221         京东方A -0.415961
601328.XSHG  2023-03-31  0.4503         交通银行 -0.366690
601816.XSHG  2023-03-31  0.4045         京沪高铁 -0.345260
000651.XSHE  2023-03-31  0.6051         格力电器 -0.342787
601288.XSHG  2023-03-31  0.3683         农业银行 -0.306676
600050.XSHG  2023-03-31  0.3339         中国联通 -0.277095
603288.XSHG  2023-03-31  0.3502         海天味业 -0.276534
600016.XSHG  2023-03-31  0.2991         民生银行 -0.267034
601988.XSHG  2023-03-31  0.2658         中国银行 -0.259549